apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hr0hctwhk-nodejs
  janus-idp.io/tekton: hr0hctwhk-nodejs
  backstage.io/kubernetes-id: hr0hctwhk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hr0hctwhk-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
