apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hr0hctwhk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hr0hctwhk-nodejs 
  name: hr0hctwhk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hr0hctwhk-nodejs 
